version: '3'
services:
  angular-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-dashboard
    networks:
      - angular-dashboard
    ports:
      - '8080:80'
networks:
  angular-dashboard:
    driver: bridge
